version: '3.7'
services:
  db:
    container_name: db
    image: mysql
    command: ["--default-authentication-plugin=mysql_native_password"]
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    networks:
      - db

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      - PMA_ARBITRARY=1
    restart: always
    ports:
      - 8080:80
    networks:
      - db
    volumes:
      - ./sessions:/sessions

  php:
    container_name: php-fpm
    build: ./php-fpm
    ports:
      - "9000:9001"
    volumes:
      - ./:/var/www/symfony:cached
    depends_on:
      - db
    networks:
      - db
      - php

  nginx:
    container_name: nginx
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - php
    networks:
      - php
    volumes:
      - ./:/var/www/symfony:cached

networks:
  db:
  php: