framework:
  workflows:
    blog_publishing:
      type: 'Workflow' # or 'state_machine'
      audit_trail:
        enabled: true
      marking_store:
        type: 'method'
        property: 'state'
      supports:
        - App\Entity\MicroPost
      initial_marking: draft
      places:
        - draft
        - reviewed
        - rejected
        - published
      transitions:
        to_review:
          from: draft
          to:   reviewed
        publish:
          from: reviewed
          to:   published
        reject:
          from: reviewed
          to:   rejected